
import Navbar from "./components/UX/UI/navbar";
import "./globals.css";


export const metadata = {
  title: "Inmobiliaria kubera",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body> 
        <Navbar></Navbar>
        {children} 
        
        </body>
    </html>
    
  );
}
